export const sampledata = [
    {
        tripId: "AB_001111",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_001112",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Confirmed",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "10/12"
    },
    {
        tripId: "AB_001113",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Cancelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "0/7"
    },
    {
        tripId: "AB_001114",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "On Tour",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_001115",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_001116",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Cancelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_001117",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_001118",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_001119",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Confirmed",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011110",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "On Tour",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011111",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011112",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Confirmed",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "10/12"
    },
    {
        tripId: "AB_0011113",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Cancelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "0/7"
    },
    {
        tripId: "AB_0011114",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "On Tour",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011115",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011116",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Cancelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011117",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011118",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Travelled",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011119",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "Confirmed",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
    {
        tripId: "AB_0011120",
        arrival: "20-06-25",
        departure: "20-06-25",
        travelMonth: "JUN",
        destination: "Singapore",
        accManager: "Pratiksha Gupta",
        bookingDate: "20-06-25",
        agent: "ABC Company Pvt Ltd",
        leadPax: "dummy text",
        orderValueInUSD: "99,999",
        paymentValueInUSD: "99,999",
        transferPrice: "IDR 30,00,000,000",
        tripStatus: "On Tour",
        opsSpoc: "dummy text",
        bookingStatus: "success",
        vouchers: "success"
    },
]